"""add relationships

Revision ID: 02ad9c3b3f4f
Revises: ad7695988b05
Create Date: 2024-01-07 22:11:43.376499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02ad9c3b3f4f"
down_revision = "ad7695988b05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("expiry", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
