"""location image remove description

Revision ID: 2db66aa9a427
Revises: e0388f48cd81
Create Date: 2024-01-20 13:21:30.734029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2db66aa9a427"
down_revision = "e0388f48cd81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.VARCHAR(length=256), nullable=False)
        )

    # ### end Alembic commands ###
