"""rename image path to name

Revision ID: 780539003720
Revises: a94d4c4a12a4
Create Date: 2024-01-08 23:53:31.328562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "780539003720"
down_revision = "a94d4c4a12a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=256), nullable=False))
        batch_op.drop_column("path")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("path", sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column("name")

    # ### end Alembic commands ###
