"""add shopping table

Revision ID: 7db07730c19b
Revises: 443a501b2981
Create Date: 2024-01-22 12:52:16.461333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7db07730c19b"
down_revision = "443a501b2981"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping",
        sa.Column("book_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id"),
    )
    with op.batch_alter_table("shopping", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shopping_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shopping", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shopping_id"))

    op.drop_table("shopping")
    # ### end Alembic commands ###
