"""add location image

Revision ID: 84a433f95d9f
Revises: 780539003720
Create Date: 2024-01-19 00:43:39.602174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84a433f95d9f"
down_revision = "780539003720"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_image",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["pickup_location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_location_image_id"), ["id"], unique=False)

    with op.batch_alter_table("pickup_location", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=256), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pickup_location", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_image_id"))

    op.drop_table("location_image")
    # ### end Alembic commands ###
