"""empty message

Revision ID: ad7695988b05
Revises: 
Create Date: 2024-01-07 15:59:13.130757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad7695988b05"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("book_id", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_image_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_id"))

    op.drop_table("image")
    # ### end Alembic commands ###
