"""location description

Revision ID: e0388f48cd81
Revises: 84a433f95d9f
Create Date: 2024-01-20 13:10:25.006707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0388f48cd81"
down_revision = "84a433f95d9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=256), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_image", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
